### PR TITLE
Milestone 4: Apple website clone - solo project

### PR DESCRIPTION
**Pull request by Cyrus-Kiprop**
## In this Apple webpage  milestone I managed to:
- use browser’s developer tools (“inspect element”)!
- Interact, style and make use of background images.
- Fill, position and align items using float and flex.
- Understand the difference between absolute and relative CSS units.
- Finally deliver on a solo project without a navigator

### CODE REVIEW

**Comment by trox115** [comment]
### Status: Changes Required 
Hello @Cyrus-Kiprop it's very nice to meet you :handshake: ! You have done a great job so far congratulations. 

Why do you have a commit from other student on a solo project?

However we need to make some changes before this project can be approved. 


**The 4 bottom images on main have a margin, you need to remove it, and make it look as similar as possible with the original**


The footer has a problem too. You need to format it like the original. 


In general the project looks really cool, congratulations :smile:  

**SUMARY**

- [ ] Remove margin from the 4 bottom pics, make width and height looks like original.

- [ ]  Format footer to improve readability, make it look like original! 

:muscle: **You got this.** 

If you have any doubt, or need help you can reach me through slack :wave: . 
António Fernandes

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Bottom part needs some styling changes.

**Comment by pelzolga123** [comment]
## Hi Cyrus, you did a good job :+1: !

Only one thing needs to be fixed and it's styling. Right now bottom part looks too big:

image


Please change it to look more like an original one:

image

### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### Hi @Cyrus-Kiprop . :clap: 

You have done well, however, our footer still breaks when zoomed in.

image

Kindly inspect the original page and see how the items were positioned so that we can have a proper clone.

 **You are almost there. Keep the good work going :+1:** 

### Status: Changes  requested.

**Review by mosesogwo — APPROVED** [review]
## :+1: Nice job meeting the requirements for this project.
Your project is approved! You may now merge to master and submit a project completion form.

Good luck in your next project.

### Status: Approved!

**Comment by Cyrus-Kiprop** [comment]
Thanks reviewers. Learned a great deal in css gradients and backgrounds.

**Pull request merged**
